// AUTO-GENERATED by generate-i18n-resources.mjs — do not edit

export const providerStrings = {
  en: {
    errorHeading: 'Error',
    invalidAppKeyError:
      "This Bible content couldn't be loaded because the app key is missing or invalid.",
  },
  af: {
    errorHeading: 'Fout',
    invalidAppKeyError:
      'Hierdie Bybelinhoud kon nie gelaai word nie omdat die toep-identifikasie ontbreek of ongeldig is.',
  },
  ar: {
    errorHeading: 'خطأ',
    invalidAppKeyError: 'تعذر تحميل محتوى الكتاب المقدس هذا لأن مفتاح التطبيق مفقود أو غير صالح.',
  },
  cs: {
    errorHeading: 'Chyba',
    invalidAppKeyError: 'Obsah Bible nelze načíst, protože klíč aplikace chybí nebo je neplatný.',
  },
  cy: {
    errorHeading: 'Gwall',
    invalidAppKeyError:
      "Ni ellid llwytho'r cynnwys Beiblaidd hwn oherwydd bod yr allwedd ap ar goll neu'n annilys.",
  },
  de: {
    errorHeading: 'Fehler',
    invalidAppKeyError:
      'Dieser Bibelinhalt konnte nicht geladen werden, da der App-Schlüssel fehlt oder ungültig ist.',
  },
  es: {
    errorHeading: 'Error',
    invalidAppKeyError:
      'Este contenido bíblico no se pudo cargar porque la clave de la aplicación falta o no es válida.',
  },
  fr: {
    errorHeading: 'Erreur',
    invalidAppKeyError:
      "Ce contenu biblique n'a pas pu être chargé car la clé d'application est manquante ou invalide.",
  },
  ko: {
    errorHeading: '오류',
    invalidAppKeyError: '앱 키가 없거나 유효하지 않아 이 성경 콘텐츠를 불러올 수 없습니다.',
  },
  no: {
    errorHeading: 'Feil',
    invalidAppKeyError:
      'Dette bibelinnholdet kunne ikke lastes fordi appnøkkelen mangler eller er ugyldig.',
  },
  pt: {
    errorHeading: 'Erro',
    invalidAppKeyError:
      'Este conteúdo bíblico não pôde ser carregado porque a chave do aplicativo está ausente ou é inválida.',
  },
  sr: {
    errorHeading: 'Greška',
    invalidAppKeyError:
      'Ovaj biblijski sadržaj nije moguće učitati jer ključ aplikacije nedostaje ili nije važeći.',
  },
  tr: {
    errorHeading: 'Hata',
    invalidAppKeyError:
      'Bu Kutsal Kitap içeriği yüklenemedi çünkü uygulama anahtarı eksik veya geçersiz.',
  },
  vi: {
    errorHeading: 'Lỗi',
    invalidAppKeyError:
      'Không thể tải nội dung Kinh Thánh này vì khóa ứng dụng bị thiếu hoặc không hợp lệ.',
  },
  zh: {
    errorHeading: '錯誤',
    invalidAppKeyError: '當應用程式 API 金鑰缺失或無效時出現的錯誤。',
  },
} as const;

export const providerStringLngs = [
  'en',
  'af',
  'ar',
  'cs',
  'cy',
  'de',
  'es',
  'fr',
  'ko',
  'no',
  'pt',
  'sr',
  'tr',
  'vi',
  'zh',
] as const;
