// AUTO-GENERATED by generate-i18n-resources.mjs — do not edit

import locale0 from './locales/en.json' with { type: 'json' };
import locale1 from './locales/es.json' with { type: 'json' };
import locale2 from './locales/fr.json' with { type: 'json' };
import locale3 from './locales/ko.json' with { type: 'json' };
import locale4 from './locales/tr.json' with { type: 'json' };
import locale5 from './locales/zh.json' with { type: 'json' };

const defaultNS = 'translation';

export const resources = {
  en: { [defaultNS]: locale0 },
  es: { [defaultNS]: locale1 },
  fr: { [defaultNS]: locale2 },
  ko: { [defaultNS]: locale3 },
  tr: { [defaultNS]: locale4 },
  zh: { [defaultNS]: locale5 },
} as const;

export const supportedLngs = Object.keys(resources);
