// AUTO-GENERATED by generate-i18n-resources.mjs — do not edit

import locale0 from './locales/en.json';
import locale1 from './locales/es.json';
import locale2 from './locales/fr.json';

const defaultNS = 'translation';

export const resources = {
  en: { [defaultNS]: locale0 },
  es: { [defaultNS]: locale1 },
  fr: { [defaultNS]: locale2 },
} as const;

export const supportedLngs = Object.keys(resources);
