// AUTO-GENERATED by generate-i18n-resources.mjs — do not edit

import en from './slim/en.json' with { type: 'json' };

const defaultNS = 'translation';

type LocaleJsonModule = { default: typeof en };

export const resources = {
  en: { [defaultNS]: en },
} as const;

export const supportedLngs = [
  'en',
  'af',
  'ar',
  'cs',
  'cy',
  'de',
  'es',
  'fr',
  'ko',
  'no',
  'pt',
  'sr',
  'tr',
  'vi',
  'zh',
] as const;

export const localeLoaders = {
  af: (): Promise<LocaleJsonModule> => import('./slim/af.json'),
  ar: (): Promise<LocaleJsonModule> => import('./slim/ar.json'),
  cs: (): Promise<LocaleJsonModule> => import('./slim/cs.json'),
  cy: (): Promise<LocaleJsonModule> => import('./slim/cy.json'),
  de: (): Promise<LocaleJsonModule> => import('./slim/de.json'),
  es: (): Promise<LocaleJsonModule> => import('./slim/es.json'),
  fr: (): Promise<LocaleJsonModule> => import('./slim/fr.json'),
  ko: (): Promise<LocaleJsonModule> => import('./slim/ko.json'),
  no: (): Promise<LocaleJsonModule> => import('./slim/no.json'),
  pt: (): Promise<LocaleJsonModule> => import('./slim/pt.json'),
  sr: (): Promise<LocaleJsonModule> => import('./slim/sr.json'),
  tr: (): Promise<LocaleJsonModule> => import('./slim/tr.json'),
  vi: (): Promise<LocaleJsonModule> => import('./slim/vi.json'),
  zh: (): Promise<LocaleJsonModule> => import('./slim/zh.json'),
};
