export type BibleBook = {
  id: BOOK_ID; // Book identifier (USFM)
  title: string;
  abbreviation?: string; // Book name abbreviation if provided by publisher
  canon: CANON;
  // eslint-disable-next-line @typescript-eslint/array-type -- Array<> syntax required for template literal type to represent chapter references
  chapters?: Array<`${BOOK_ID}.${number | `INTRO${number}`}`>; // Ordered list of chapter ids for given Bible and book (e.g., ["GEN.1", "GEN.2", "3JN.INTRO1", "3JN.1"])
};

export type BOOK_ID =
  | 'GEN'
  | 'EXO'
  | 'LEV'
  | 'NUM'
  | 'DEU'
  | 'JOS'
  | 'JDG'
  | 'RUT'
  | '1SA'
  | '2SA'
  | '1KI'
  | '2KI'
  | '1CH'
  | '2CH'
  | 'EZR'
  | 'NEH'
  | 'EST'
  | 'JOB'
  | 'PSA'
  | 'PRO'
  | 'ECC'
  | 'SNG'
  | 'ISA'
  | 'JER'
  | 'LAM'
  | 'EZK'
  | 'DAN'
  | 'HOS'
  | 'JOL'
  | 'AMO'
  | 'OBA'
  | 'JON'
  | 'MIC'
  | 'NAM'
  | 'HAB'
  | 'ZEP'
  | 'HAG'
  | 'ZEC'
  | 'MAL'
  | 'MAT'
  | 'MRK'
  | 'LUK'
  | 'JHN'
  | 'ACT'
  | 'ROM'
  | '1CO'
  | '2CO'
  | 'GAL'
  | 'EPH'
  | 'PHP'
  | 'COL'
  | '1TH'
  | '2TH'
  | '1TI'
  | '2TI'
  | 'TIT'
  | 'PHM'
  | 'HEB'
  | 'JAS'
  | '1PE'
  | '2PE'
  | '1JN'
  | '2JN'
  | '3JN'
  | 'JUD'
  | 'REV'
  | 'TOB'
  | 'JDT'
  | 'ESG'
  | 'WIS'
  | 'SIR'
  | 'BAR'
  | 'LJE'
  | 'S3Y'
  | 'SUS'
  | 'BEL'
  | '1MA'
  | '2MA'
  | '3MA'
  | '4MA'
  | '1ES'
  | '2ES'
  | 'MAN'
  | 'PS2'
  | 'ODA'
  | 'PSS'
  | '3ES'
  | 'EZA'
  | '5EZ'
  | '6EZ'
  | 'DAG'
  | 'PS3'
  | '2BA'
  | 'LBA'
  | 'JUB'
  | 'ENO'
  | '1MQ'
  | '2MQ'
  | '3MQ'
  | 'REP'
  | '4BA'
  | 'LAO'
  | 'LKA'
  | (string & {});

export type CANON = 'old_testament' | 'new_testament' | 'deuterocanon';
