// React SDK main entry point

export * from './components';
export * from './types';

// Named value re-exports (not `export *`) so a Provider-only import does not
// evaluate the whole core barrel. Types come from `./types`.
export {
  ApiClient,
  BIBLE_CONTAINER_ATTRIBUTES,
  BIBLE_CSS_STYLESHEET_URL,
  BOOK_CANON,
  BOOK_IDS,
  BibleClient,
  CANON_IDS,
  DEFAULT_LICENSE_FREE_BIBLE_VERSION,
  DataExchangeClient,
  HighlightsClient,
  LanguagesClient,
  MAX_SEARCH_QUERY_GRAPHEMES,
  MemoryStorageStrategy,
  MissingPassageAttributionError,
  OrganizationsClient,
  SDK_NAME,
  SDK_VERSION,
  SDK_VERSION_HEADER_NAME,
  SearchClient,
  SessionStorageStrategy,
  SignInWithYouVersionPermission,
  SignInWithYouVersionResult,
  UNTITLED_SERIF_FONT_ID,
  YouVersionAPI,
  YouVersionAPIUsers,
  YouVersionPlatformConfiguration,
  YouVersionUserInfo,
  __resetAuthCallbackDedupeForTests,
  __resetTokenRefreshDedupeForTests,
  buildDataExchangeUrl,
  buildSdkVersionHeaderValue,
  clampSearchText,
  clearStorage,
  collectFilteredPage,
  fieldsNeededForLanguageFilter,
  fieldsNeededForVersionFilter,
  getAdjacentChapter,
  getAllVOTDs,
  getBibleStylesheets,
  getBook,
  getBooks,
  getChapter,
  getChapters,
  getHttpStatus,
  getLanguage,
  getLanguages,
  getLocalStorage,
  getPassage,
  getPassageDisplay,
  getSessionStorage,
  getSuggestedQueries,
  getTrendingQueries,
  getVOTD,
  getVerse,
  getVerses,
  getVersion,
  getVersionFilterSnapshot,
  getVersions,
  handleDataExchangeCallback,
  isUsableBibleVersion,
  isUsableLanguageTag,
  isValidStructuralUsfmReference,
  isVersionFilterActive,
  isVersionIdDecidablyUnusable,
  parseDataExchangeCallback,
  parseGrantedPermissions,
  parseSearchLanguageRange,
  parseUsfmReference,
  removeStorageItem,
  searchTopics,
  searchVerses,
  setStorageItem,
  throwUnusableBibleVersion,
  transformBibleHtml,
  type ApiConfig,
  type AuthenticationState,
  type Highlight,
} from '@youversion/platform-core';

export {
  YouVersionProvider as BaseYouVersionProvider,
  useYVAuth,
  type UseYVAuthReturn,
} from '@youversion/platform-react-hooks';

export { YouVersionProvider, type YouVersionProviderProps } from './components/YouVersionProvider';
