/**
 * The Berean Standard Bible does not require a license
 * to use via the YouVersion Platform, qualifying it as
 * a good use-case for a default Bible Version.
 */
export const DEFAULT_LICENSE_FREE_BIBLE_VERSION = 3034 as const;

export const BOOK_IDS = [
  'GEN',
  'EXO',
  'LEV',
  'NUM',
  'DEU',
  'JOS',
  'JDG',
  'RUT',
  '1SA',
  '2SA',
  '1KI',
  '2KI',
  '1CH',
  '2CH',
  'EZR',
  'NEH',
  'EST',
  'JOB',
  'PSA',
  'PRO',
  'ECC',
  'SNG',
  'ISA',
  'JER',
  'LAM',
  'EZK',
  'DAN',
  'HOS',
  'JOL',
  'AMO',
  'OBA',
  'JON',
  'MIC',
  'NAM',
  'HAB',
  'ZEP',
  'HAG',
  'ZEC',
  'MAL',
  'MAT',
  'MRK',
  'LUK',
  'JHN',
  'ACT',
  'ROM',
  '1CO',
  '2CO',
  'GAL',
  'EPH',
  'PHP',
  'COL',
  '1TH',
  '2TH',
  '1TI',
  '2TI',
  'TIT',
  'PHM',
  'HEB',
  'JAS',
  '1PE',
  '2PE',
  '1JN',
  '2JN',
  '3JN',
  'JUD',
  'REV',
  // dc (Apocrypha) books
  'TOB',
  'JDT',
  'ESG',
  'WIS',
  'SIR',
  'BAR',
  'LJE',
  'S3Y',
  'SUS',
  'BEL',
  '1MA',
  '2MA',
  '3MA',
  '4MA',
  '1ES',
  '2ES',
  'MAN',
  'PS2',
  'ODA',
  'PSS',
  '3ES',
  'EZA',
  '5EZ',
  '6EZ',
  'DAG',
  'PS3',
  '2BA',
  'LBA',
  'JUB',
  'ENO',
  '1MQ',
  '2MQ',
  '3MQ',
  'REP',
  '4BA',
  'LAO',
  // Luke-Acts combo, treated canonically as New Testament
  'LKA',
] as const;

// Import types for BOOK_CANON - moved CANON_IDS to schemas/book.ts to avoid circular dependency
import type { Canon, BookUsfm } from '../schemas/book';

/**
 * @see https://github.com/youversion/usfm-references/blob/main/usfm_references/books.py
 */
export const BOOK_CANON: Record<BookUsfm, Canon> = {
  GEN: 'old_testament',
  EXO: 'old_testament',
  LEV: 'old_testament',
  NUM: 'old_testament',
  DEU: 'old_testament',
  JOS: 'old_testament',
  JDG: 'old_testament',
  RUT: 'old_testament',
  '1SA': 'old_testament',
  '2SA': 'old_testament',
  '1KI': 'old_testament',
  '2KI': 'old_testament',
  '1CH': 'old_testament',
  '2CH': 'old_testament',
  EZR: 'old_testament',
  NEH: 'old_testament',
  EST: 'old_testament',
  JOB: 'old_testament',
  PSA: 'old_testament',
  PRO: 'old_testament',
  ECC: 'old_testament',
  SNG: 'old_testament',
  ISA: 'old_testament',
  JER: 'old_testament',
  LAM: 'old_testament',
  EZK: 'old_testament',
  DAN: 'old_testament',
  HOS: 'old_testament',
  JOL: 'old_testament',
  AMO: 'old_testament',
  OBA: 'old_testament',
  JON: 'old_testament',
  MIC: 'old_testament',
  NAM: 'old_testament',
  HAB: 'old_testament',
  ZEP: 'old_testament',
  HAG: 'old_testament',
  ZEC: 'old_testament',
  MAL: 'old_testament',
  MAT: 'new_testament',
  MRK: 'new_testament',
  LUK: 'new_testament',
  JHN: 'new_testament',
  ACT: 'new_testament',
  ROM: 'new_testament',
  '1CO': 'new_testament',
  '2CO': 'new_testament',
  GAL: 'new_testament',
  EPH: 'new_testament',
  PHP: 'new_testament',
  COL: 'new_testament',
  '1TH': 'new_testament',
  '2TH': 'new_testament',
  '1TI': 'new_testament',
  '2TI': 'new_testament',
  TIT: 'new_testament',
  PHM: 'new_testament',
  HEB: 'new_testament',
  JAS: 'new_testament',
  '1PE': 'new_testament',
  '2PE': 'new_testament',
  '1JN': 'new_testament',
  '2JN': 'new_testament',
  '3JN': 'new_testament',
  JUD: 'new_testament',
  REV: 'new_testament',
  TOB: 'deuterocanon',
  JDT: 'deuterocanon',
  ESG: 'deuterocanon',
  WIS: 'deuterocanon',
  SIR: 'deuterocanon',
  BAR: 'deuterocanon',
  LJE: 'deuterocanon',
  S3Y: 'deuterocanon',
  SUS: 'deuterocanon',
  BEL: 'deuterocanon',
  '1MA': 'deuterocanon',
  '2MA': 'deuterocanon',
  '3MA': 'deuterocanon',
  '4MA': 'deuterocanon',
  '1ES': 'deuterocanon',
  '2ES': 'deuterocanon',
  MAN: 'deuterocanon',
  PS2: 'deuterocanon',
  ODA: 'deuterocanon',
  PSS: 'deuterocanon',
  '3ES': 'deuterocanon',
  EZA: 'deuterocanon',
  '5EZ': 'deuterocanon',
  '6EZ': 'deuterocanon',
  DAG: 'deuterocanon',
  PS3: 'deuterocanon',
  '2BA': 'deuterocanon',
  LBA: 'deuterocanon',
  JUB: 'deuterocanon',
  ENO: 'deuterocanon',
  '1MQ': 'deuterocanon',
  '2MQ': 'deuterocanon',
  '3MQ': 'deuterocanon',
  REP: 'deuterocanon',
  '4BA': 'deuterocanon',
  LAO: 'deuterocanon',
  LKA: 'new_testament', // Luke-Acts combo, treated canonically as New Testament
};
