export const mockBibleGenesis = {
  id: 'GEN',
  title: 'Genesis',
  abbreviation: 'Gen',
  canon: 'ot',
  chapters: [
    'GEN.1',
    'GEN.2',
    'GEN.3',
    'GEN.4',
    'GEN.5',
    'GEN.6',
    'GEN.7',
    'GEN.8',
    'GEN.9',
    'GEN.10',
    'GEN.11',
    'GEN.12',
    'GEN.13',
    'GEN.14',
    'GEN.15',
    'GEN.16',
    'GEN.17',
    'GEN.18',
    'GEN.19',
    'GEN.20',
    'GEN.21',
    'GEN.22',
    'GEN.23',
    'GEN.24',
    'GEN.25',
    'GEN.26',
    'GEN.27',
    'GEN.28',
    'GEN.29',
    'GEN.30',
    'GEN.31',
    'GEN.32',
    'GEN.33',
    'GEN.34',
    'GEN.35',
    'GEN.36',
    'GEN.37',
    'GEN.38',
    'GEN.39',
    'GEN.40',
    'GEN.41',
    'GEN.42',
    'GEN.43',
    'GEN.44',
    'GEN.45',
    'GEN.46',
    'GEN.47',
    'GEN.48',
    'GEN.49',
    'GEN.50',
  ],
};
export const mockBibleBooks = [
  {
    id: 'GEN',
    title: 'Genesis',
    abbreviation: 'Gen',
    canon: 'ot',
    chapters: [
      'GEN.1',
      'GEN.2',
      'GEN.3',
      'GEN.4',
      'GEN.5',
      'GEN.6',
      'GEN.7',
      'GEN.8',
      'GEN.9',
      'GEN.10',
      'GEN.11',
      'GEN.12',
      'GEN.13',
      'GEN.14',
      'GEN.15',
      'GEN.16',
      'GEN.17',
      'GEN.18',
      'GEN.19',
      'GEN.20',
      'GEN.21',
      'GEN.22',
      'GEN.23',
      'GEN.24',
      'GEN.25',
      'GEN.26',
      'GEN.27',
      'GEN.28',
      'GEN.29',
      'GEN.30',
      'GEN.31',
      'GEN.32',
      'GEN.33',
      'GEN.34',
      'GEN.35',
      'GEN.36',
      'GEN.37',
      'GEN.38',
      'GEN.39',
      'GEN.40',
      'GEN.41',
      'GEN.42',
      'GEN.43',
      'GEN.44',
      'GEN.45',
      'GEN.46',
      'GEN.47',
      'GEN.48',
      'GEN.49',
      'GEN.50',
    ],
  },
  {
    id: 'EXO',
    title: 'Exodus',
    abbreviation: 'Exod',
    canon: 'ot',
    chapters: [
      'EXO.1',
      'EXO.2',
      'EXO.3',
      'EXO.4',
      'EXO.5',
      'EXO.6',
      'EXO.7',
      'EXO.8',
      'EXO.9',
      'EXO.10',
      'EXO.11',
      'EXO.12',
      'EXO.13',
      'EXO.14',
      'EXO.15',
      'EXO.16',
      'EXO.17',
      'EXO.18',
      'EXO.19',
      'EXO.20',
      'EXO.21',
      'EXO.22',
      'EXO.23',
      'EXO.24',
      'EXO.25',
      'EXO.26',
      'EXO.27',
      'EXO.28',
      'EXO.29',
      'EXO.30',
      'EXO.31',
      'EXO.32',
      'EXO.33',
      'EXO.34',
      'EXO.35',
      'EXO.36',
      'EXO.37',
      'EXO.38',
      'EXO.39',
      'EXO.40',
    ],
  },
  {
    id: 'LEV',
    title: 'Leviticus',
    abbreviation: 'Lev',
    canon: 'ot',
    chapters: [
      'LEV.1',
      'LEV.2',
      'LEV.3',
      'LEV.4',
      'LEV.5',
      'LEV.6',
      'LEV.7',
      'LEV.8',
      'LEV.9',
      'LEV.10',
      'LEV.11',
      'LEV.12',
      'LEV.13',
      'LEV.14',
      'LEV.15',
      'LEV.16',
      'LEV.17',
      'LEV.18',
      'LEV.19',
      'LEV.20',
      'LEV.21',
      'LEV.22',
      'LEV.23',
      'LEV.24',
      'LEV.25',
      'LEV.26',
      'LEV.27',
    ],
  },
  {
    id: 'NUM',
    title: 'Numbers',
    abbreviation: 'Num',
    canon: 'ot',
    chapters: [
      'NUM.1',
      'NUM.2',
      'NUM.3',
      'NUM.4',
      'NUM.5',
      'NUM.6',
      'NUM.7',
      'NUM.8',
      'NUM.9',
      'NUM.10',
      'NUM.11',
      'NUM.12',
      'NUM.13',
      'NUM.14',
      'NUM.15',
      'NUM.16',
      'NUM.17',
      'NUM.18',
      'NUM.19',
      'NUM.20',
      'NUM.21',
      'NUM.22',
      'NUM.23',
      'NUM.24',
      'NUM.25',
      'NUM.26',
      'NUM.27',
      'NUM.28',
      'NUM.29',
      'NUM.30',
      'NUM.31',
      'NUM.32',
      'NUM.33',
      'NUM.34',
      'NUM.35',
      'NUM.36',
    ],
  },
  {
    id: 'DEU',
    title: 'Deuteronomy',
    abbreviation: 'Deut',
    canon: 'ot',
    chapters: [
      'DEU.1',
      'DEU.2',
      'DEU.3',
      'DEU.4',
      'DEU.5',
      'DEU.6',
      'DEU.7',
      'DEU.8',
      'DEU.9',
      'DEU.10',
      'DEU.11',
      'DEU.12',
      'DEU.13',
      'DEU.14',
      'DEU.15',
      'DEU.16',
      'DEU.17',
      'DEU.18',
      'DEU.19',
      'DEU.20',
      'DEU.21',
      'DEU.22',
      'DEU.23',
      'DEU.24',
      'DEU.25',
      'DEU.26',
      'DEU.27',
      'DEU.28',
      'DEU.29',
      'DEU.30',
      'DEU.31',
      'DEU.32',
      'DEU.33',
      'DEU.34',
    ],
  },
  {
    id: 'JOS',
    title: 'Joshua',
    abbreviation: 'Josh',
    canon: 'ot',
    chapters: [
      'JOS.1',
      'JOS.2',
      'JOS.3',
      'JOS.4',
      'JOS.5',
      'JOS.6',
      'JOS.7',
      'JOS.8',
      'JOS.9',
      'JOS.10',
      'JOS.11',
      'JOS.12',
      'JOS.13',
      'JOS.14',
      'JOS.15',
      'JOS.16',
      'JOS.17',
      'JOS.18',
      'JOS.19',
      'JOS.20',
      'JOS.21',
      'JOS.22',
      'JOS.23',
      'JOS.24',
    ],
  },
  {
    id: 'JDG',
    title: 'Judges',
    abbreviation: 'Judg',
    canon: 'ot',
    chapters: [
      'JDG.1',
      'JDG.2',
      'JDG.3',
      'JDG.4',
      'JDG.5',
      'JDG.6',
      'JDG.7',
      'JDG.8',
      'JDG.9',
      'JDG.10',
      'JDG.11',
      'JDG.12',
      'JDG.13',
      'JDG.14',
      'JDG.15',
      'JDG.16',
      'JDG.17',
      'JDG.18',
      'JDG.19',
      'JDG.20',
      'JDG.21',
    ],
  },
  {
    id: 'RUT',
    title: 'Ruth',
    abbreviation: 'Ruth',
    canon: 'ot',
    chapters: ['RUT.1', 'RUT.2', 'RUT.3', 'RUT.4'],
  },
  {
    id: '1SA',
    title: '1 Samuel',
    abbreviation: '1 Sam',
    canon: 'ot',
    chapters: [
      '1SA.1',
      '1SA.2',
      '1SA.3',
      '1SA.4',
      '1SA.5',
      '1SA.6',
      '1SA.7',
      '1SA.8',
      '1SA.9',
      '1SA.10',
      '1SA.11',
      '1SA.12',
      '1SA.13',
      '1SA.14',
      '1SA.15',
      '1SA.16',
      '1SA.17',
      '1SA.18',
      '1SA.19',
      '1SA.20',
      '1SA.21',
      '1SA.22',
      '1SA.23',
      '1SA.24',
      '1SA.25',
      '1SA.26',
      '1SA.27',
      '1SA.28',
      '1SA.29',
      '1SA.30',
      '1SA.31',
    ],
  },
  {
    id: '2SA',
    title: '2 Samuel',
    abbreviation: '2 Sam',
    canon: 'ot',
    chapters: [
      '2SA.1',
      '2SA.2',
      '2SA.3',
      '2SA.4',
      '2SA.5',
      '2SA.6',
      '2SA.7',
      '2SA.8',
      '2SA.9',
      '2SA.10',
      '2SA.11',
      '2SA.12',
      '2SA.13',
      '2SA.14',
      '2SA.15',
      '2SA.16',
      '2SA.17',
      '2SA.18',
      '2SA.19',
      '2SA.20',
      '2SA.21',
      '2SA.22',
      '2SA.23',
      '2SA.24',
    ],
  },
  {
    id: '1KI',
    title: '1 Kings',
    abbreviation: '1 Kgs',
    canon: 'ot',
    chapters: [
      '1KI.1',
      '1KI.2',
      '1KI.3',
      '1KI.4',
      '1KI.5',
      '1KI.6',
      '1KI.7',
      '1KI.8',
      '1KI.9',
      '1KI.10',
      '1KI.11',
      '1KI.12',
      '1KI.13',
      '1KI.14',
      '1KI.15',
      '1KI.16',
      '1KI.17',
      '1KI.18',
      '1KI.19',
      '1KI.20',
      '1KI.21',
      '1KI.22',
    ],
  },
  {
    id: '2KI',
    title: '2 Kings',
    abbreviation: '2 Kgs',
    canon: 'ot',
    chapters: [
      '2KI.1',
      '2KI.2',
      '2KI.3',
      '2KI.4',
      '2KI.5',
      '2KI.6',
      '2KI.7',
      '2KI.8',
      '2KI.9',
      '2KI.10',
      '2KI.11',
      '2KI.12',
      '2KI.13',
      '2KI.14',
      '2KI.15',
      '2KI.16',
      '2KI.17',
      '2KI.18',
      '2KI.19',
      '2KI.20',
      '2KI.21',
      '2KI.22',
      '2KI.23',
      '2KI.24',
      '2KI.25',
    ],
  },
  {
    id: '1CH',
    title: '1 Chronicles',
    abbreviation: '1 Chr',
    canon: 'ot',
    chapters: [
      '1CH.1',
      '1CH.2',
      '1CH.3',
      '1CH.4',
      '1CH.5',
      '1CH.6',
      '1CH.7',
      '1CH.8',
      '1CH.9',
      '1CH.10',
      '1CH.11',
      '1CH.12',
      '1CH.13',
      '1CH.14',
      '1CH.15',
      '1CH.16',
      '1CH.17',
      '1CH.18',
      '1CH.19',
      '1CH.20',
      '1CH.21',
      '1CH.22',
      '1CH.23',
      '1CH.24',
      '1CH.25',
      '1CH.26',
      '1CH.27',
      '1CH.28',
      '1CH.29',
    ],
  },
  {
    id: '2CH',
    title: '2 Chronicles',
    abbreviation: '2 Chr',
    canon: 'ot',
    chapters: [
      '2CH.1',
      '2CH.2',
      '2CH.3',
      '2CH.4',
      '2CH.5',
      '2CH.6',
      '2CH.7',
      '2CH.8',
      '2CH.9',
      '2CH.10',
      '2CH.11',
      '2CH.12',
      '2CH.13',
      '2CH.14',
      '2CH.15',
      '2CH.16',
      '2CH.17',
      '2CH.18',
      '2CH.19',
      '2CH.20',
      '2CH.21',
      '2CH.22',
      '2CH.23',
      '2CH.24',
      '2CH.25',
      '2CH.26',
      '2CH.27',
      '2CH.28',
      '2CH.29',
      '2CH.30',
      '2CH.31',
      '2CH.32',
      '2CH.33',
      '2CH.34',
      '2CH.35',
      '2CH.36',
    ],
  },
  {
    id: 'EZR',
    title: 'Ezra',
    abbreviation: 'Ezra',
    canon: 'ot',
    chapters: [
      'EZR.1',
      'EZR.2',
      'EZR.3',
      'EZR.4',
      'EZR.5',
      'EZR.6',
      'EZR.7',
      'EZR.8',
      'EZR.9',
      'EZR.10',
    ],
  },
  {
    id: 'NEH',
    title: 'Nehemiah',
    abbreviation: 'Neh',
    canon: 'ot',
    chapters: [
      'NEH.1',
      'NEH.2',
      'NEH.3',
      'NEH.4',
      'NEH.5',
      'NEH.6',
      'NEH.7',
      'NEH.8',
      'NEH.9',
      'NEH.10',
      'NEH.11',
      'NEH.12',
      'NEH.13',
    ],
  },
  {
    id: 'EST',
    title: 'Esther',
    abbreviation: 'Esth',
    canon: 'ot',
    chapters: [
      'EST.1',
      'EST.2',
      'EST.3',
      'EST.4',
      'EST.5',
      'EST.6',
      'EST.7',
      'EST.8',
      'EST.9',
      'EST.10',
    ],
  },
  {
    id: 'JOB',
    title: 'Job',
    abbreviation: 'Job',
    canon: 'ot',
    chapters: [
      'JOB.1',
      'JOB.2',
      'JOB.3',
      'JOB.4',
      'JOB.5',
      'JOB.6',
      'JOB.7',
      'JOB.8',
      'JOB.9',
      'JOB.10',
      'JOB.11',
      'JOB.12',
      'JOB.13',
      'JOB.14',
      'JOB.15',
      'JOB.16',
      'JOB.17',
      'JOB.18',
      'JOB.19',
      'JOB.20',
      'JOB.21',
      'JOB.22',
      'JOB.23',
      'JOB.24',
      'JOB.25',
      'JOB.26',
      'JOB.27',
      'JOB.28',
      'JOB.29',
      'JOB.30',
      'JOB.31',
      'JOB.32',
      'JOB.33',
      'JOB.34',
      'JOB.35',
      'JOB.36',
      'JOB.37',
      'JOB.38',
      'JOB.39',
      'JOB.40',
      'JOB.41',
      'JOB.42',
    ],
  },
  {
    id: 'PSA',
    title: 'Psalm',
    abbreviation: 'Ps',
    canon: 'ot',
    chapters: [
      'PSA.1',
      'PSA.2',
      'PSA.3',
      'PSA.4',
      'PSA.5',
      'PSA.6',
      'PSA.7',
      'PSA.8',
      'PSA.9',
      'PSA.10',
      'PSA.11',
      'PSA.12',
      'PSA.13',
      'PSA.14',
      'PSA.15',
      'PSA.16',
      'PSA.17',
      'PSA.18',
      'PSA.19',
      'PSA.20',
      'PSA.21',
      'PSA.22',
      'PSA.23',
      'PSA.24',
      'PSA.25',
      'PSA.26',
      'PSA.27',
      'PSA.28',
      'PSA.29',
      'PSA.30',
      'PSA.31',
      'PSA.32',
      'PSA.33',
      'PSA.34',
      'PSA.35',
      'PSA.36',
      'PSA.37',
      'PSA.38',
      'PSA.39',
      'PSA.40',
      'PSA.41',
      'PSA.42',
      'PSA.43',
      'PSA.44',
      'PSA.45',
      'PSA.46',
      'PSA.47',
      'PSA.48',
      'PSA.49',
      'PSA.50',
      'PSA.51',
      'PSA.52',
      'PSA.53',
      'PSA.54',
      'PSA.55',
      'PSA.56',
      'PSA.57',
      'PSA.58',
      'PSA.59',
      'PSA.60',
      'PSA.61',
      'PSA.62',
      'PSA.63',
      'PSA.64',
      'PSA.65',
      'PSA.66',
      'PSA.67',
      'PSA.68',
      'PSA.69',
      'PSA.70',
      'PSA.71',
      'PSA.72',
      'PSA.73',
      'PSA.74',
      'PSA.75',
      'PSA.76',
      'PSA.77',
      'PSA.78',
      'PSA.79',
      'PSA.80',
      'PSA.81',
      'PSA.82',
      'PSA.83',
      'PSA.84',
      'PSA.85',
      'PSA.86',
      'PSA.87',
      'PSA.88',
      'PSA.89',
      'PSA.90',
      'PSA.91',
      'PSA.92',
      'PSA.93',
      'PSA.94',
      'PSA.95',
      'PSA.96',
      'PSA.97',
      'PSA.98',
      'PSA.99',
      'PSA.100',
      'PSA.101',
      'PSA.102',
      'PSA.103',
      'PSA.104',
      'PSA.105',
      'PSA.106',
      'PSA.107',
      'PSA.108',
      'PSA.109',
      'PSA.110',
      'PSA.111',
      'PSA.112',
      'PSA.113',
      'PSA.114',
      'PSA.115',
      'PSA.116',
      'PSA.117',
      'PSA.118',
      'PSA.119',
      'PSA.120',
      'PSA.121',
      'PSA.122',
      'PSA.123',
      'PSA.124',
      'PSA.125',
      'PSA.126',
      'PSA.127',
      'PSA.128',
      'PSA.129',
      'PSA.130',
      'PSA.131',
      'PSA.132',
      'PSA.133',
      'PSA.134',
      'PSA.135',
      'PSA.136',
      'PSA.137',
      'PSA.138',
      'PSA.139',
      'PSA.140',
      'PSA.141',
      'PSA.142',
      'PSA.143',
      'PSA.144',
      'PSA.145',
      'PSA.146',
      'PSA.147',
      'PSA.148',
      'PSA.149',
      'PSA.150',
    ],
  },
  {
    id: 'PRO',
    title: 'Proverbs',
    abbreviation: 'Prov',
    canon: 'ot',
    chapters: [
      'PRO.1',
      'PRO.2',
      'PRO.3',
      'PRO.4',
      'PRO.5',
      'PRO.6',
      'PRO.7',
      'PRO.8',
      'PRO.9',
      'PRO.10',
      'PRO.11',
      'PRO.12',
      'PRO.13',
      'PRO.14',
      'PRO.15',
      'PRO.16',
      'PRO.17',
      'PRO.18',
      'PRO.19',
      'PRO.20',
      'PRO.21',
      'PRO.22',
      'PRO.23',
      'PRO.24',
      'PRO.25',
      'PRO.26',
      'PRO.27',
      'PRO.28',
      'PRO.29',
      'PRO.30',
      'PRO.31',
    ],
  },
  {
    id: 'ECC',
    title: 'Ecclesiastes',
    abbreviation: 'Eccl',
    canon: 'ot',
    chapters: [
      'ECC.1',
      'ECC.2',
      'ECC.3',
      'ECC.4',
      'ECC.5',
      'ECC.6',
      'ECC.7',
      'ECC.8',
      'ECC.9',
      'ECC.10',
      'ECC.11',
      'ECC.12',
    ],
  },
  {
    id: 'SNG',
    title: 'Song of Solomon',
    abbreviation: 'Song',
    canon: 'ot',
    chapters: ['SNG.1', 'SNG.2', 'SNG.3', 'SNG.4', 'SNG.5', 'SNG.6', 'SNG.7', 'SNG.8'],
  },
  {
    id: 'ISA',
    title: 'Isaiah',
    abbreviation: 'Isa',
    canon: 'ot',
    chapters: [
      'ISA.1',
      'ISA.2',
      'ISA.3',
      'ISA.4',
      'ISA.5',
      'ISA.6',
      'ISA.7',
      'ISA.8',
      'ISA.9',
      'ISA.10',
      'ISA.11',
      'ISA.12',
      'ISA.13',
      'ISA.14',
      'ISA.15',
      'ISA.16',
      'ISA.17',
      'ISA.18',
      'ISA.19',
      'ISA.20',
      'ISA.21',
      'ISA.22',
      'ISA.23',
      'ISA.24',
      'ISA.25',
      'ISA.26',
      'ISA.27',
      'ISA.28',
      'ISA.29',
      'ISA.30',
      'ISA.31',
      'ISA.32',
      'ISA.33',
      'ISA.34',
      'ISA.35',
      'ISA.36',
      'ISA.37',
      'ISA.38',
      'ISA.39',
      'ISA.40',
      'ISA.41',
      'ISA.42',
      'ISA.43',
      'ISA.44',
      'ISA.45',
      'ISA.46',
      'ISA.47',
      'ISA.48',
      'ISA.49',
      'ISA.50',
      'ISA.51',
      'ISA.52',
      'ISA.53',
      'ISA.54',
      'ISA.55',
      'ISA.56',
      'ISA.57',
      'ISA.58',
      'ISA.59',
      'ISA.60',
      'ISA.61',
      'ISA.62',
      'ISA.63',
      'ISA.64',
      'ISA.65',
      'ISA.66',
    ],
  },
  {
    id: 'JER',
    title: 'Jeremiah',
    abbreviation: 'Jer',
    canon: 'ot',
    chapters: [
      'JER.1',
      'JER.2',
      'JER.3',
      'JER.4',
      'JER.5',
      'JER.6',
      'JER.7',
      'JER.8',
      'JER.9',
      'JER.10',
      'JER.11',
      'JER.12',
      'JER.13',
      'JER.14',
      'JER.15',
      'JER.16',
      'JER.17',
      'JER.18',
      'JER.19',
      'JER.20',
      'JER.21',
      'JER.22',
      'JER.23',
      'JER.24',
      'JER.25',
      'JER.26',
      'JER.27',
      'JER.28',
      'JER.29',
      'JER.30',
      'JER.31',
      'JER.32',
      'JER.33',
      'JER.34',
      'JER.35',
      'JER.36',
      'JER.37',
      'JER.38',
      'JER.39',
      'JER.40',
      'JER.41',
      'JER.42',
      'JER.43',
      'JER.44',
      'JER.45',
      'JER.46',
      'JER.47',
      'JER.48',
      'JER.49',
      'JER.50',
      'JER.51',
      'JER.52',
    ],
  },
  {
    id: 'LAM',
    title: 'Lamentations',
    abbreviation: 'Lam',
    canon: 'ot',
    chapters: ['LAM.1', 'LAM.2', 'LAM.3', 'LAM.4', 'LAM.5'],
  },
  {
    id: 'EZK',
    title: 'Ezekiel',
    abbreviation: 'Ezek',
    canon: 'ot',
    chapters: [
      'EZK.1',
      'EZK.2',
      'EZK.3',
      'EZK.4',
      'EZK.5',
      'EZK.6',
      'EZK.7',
      'EZK.8',
      'EZK.9',
      'EZK.10',
      'EZK.11',
      'EZK.12',
      'EZK.13',
      'EZK.14',
      'EZK.15',
      'EZK.16',
      'EZK.17',
      'EZK.18',
      'EZK.19',
      'EZK.20',
      'EZK.21',
      'EZK.22',
      'EZK.23',
      'EZK.24',
      'EZK.25',
      'EZK.26',
      'EZK.27',
      'EZK.28',
      'EZK.29',
      'EZK.30',
      'EZK.31',
      'EZK.32',
      'EZK.33',
      'EZK.34',
      'EZK.35',
      'EZK.36',
      'EZK.37',
      'EZK.38',
      'EZK.39',
      'EZK.40',
      'EZK.41',
      'EZK.42',
      'EZK.43',
      'EZK.44',
      'EZK.45',
      'EZK.46',
      'EZK.47',
      'EZK.48',
    ],
  },
  {
    id: 'DAN',
    title: 'Daniel',
    abbreviation: 'Dan',
    canon: 'ot',
    chapters: [
      'DAN.1',
      'DAN.2',
      'DAN.3',
      'DAN.4',
      'DAN.5',
      'DAN.6',
      'DAN.7',
      'DAN.8',
      'DAN.9',
      'DAN.10',
      'DAN.11',
      'DAN.12',
    ],
  },
  {
    id: 'HOS',
    title: 'Hosea',
    abbreviation: 'Hos',
    canon: 'ot',
    chapters: [
      'HOS.1',
      'HOS.2',
      'HOS.3',
      'HOS.4',
      'HOS.5',
      'HOS.6',
      'HOS.7',
      'HOS.8',
      'HOS.9',
      'HOS.10',
      'HOS.11',
      'HOS.12',
      'HOS.13',
      'HOS.14',
    ],
  },
  {
    id: 'JOL',
    title: 'Joel',
    abbreviation: 'Joel',
    canon: 'ot',
    chapters: ['JOL.1', 'JOL.2', 'JOL.3'],
  },
  {
    id: 'AMO',
    title: 'Amos',
    abbreviation: 'Amos',
    canon: 'ot',
    chapters: ['AMO.1', 'AMO.2', 'AMO.3', 'AMO.4', 'AMO.5', 'AMO.6', 'AMO.7', 'AMO.8', 'AMO.9'],
  },
  {
    id: 'OBA',
    title: 'Obadiah',
    abbreviation: 'Obad',
    canon: 'ot',
    chapters: ['OBA.1'],
  },
  {
    id: 'JON',
    title: 'Jonah',
    abbreviation: 'Jonah',
    canon: 'ot',
    chapters: ['JON.1', 'JON.2', 'JON.3', 'JON.4'],
  },
  {
    id: 'MIC',
    title: 'Micah',
    abbreviation: 'Mic',
    canon: 'ot',
    chapters: ['MIC.1', 'MIC.2', 'MIC.3', 'MIC.4', 'MIC.5', 'MIC.6', 'MIC.7'],
  },
  {
    id: 'NAM',
    title: 'Nahum',
    abbreviation: 'Nah',
    canon: 'ot',
    chapters: ['NAM.1', 'NAM.2', 'NAM.3'],
  },
  {
    id: 'HAB',
    title: 'Habakkuk',
    abbreviation: 'Hab',
    canon: 'ot',
    chapters: ['HAB.1', 'HAB.2', 'HAB.3'],
  },
  {
    id: 'ZEP',
    title: 'Zephaniah',
    abbreviation: 'Zeph',
    canon: 'ot',
    chapters: ['ZEP.1', 'ZEP.2', 'ZEP.3'],
  },
  {
    id: 'HAG',
    title: 'Haggai',
    abbreviation: 'Hag',
    canon: 'ot',
    chapters: ['HAG.1', 'HAG.2'],
  },
  {
    id: 'ZEC',
    title: 'Zechariah',
    abbreviation: 'Zech',
    canon: 'ot',
    chapters: [
      'ZEC.1',
      'ZEC.2',
      'ZEC.3',
      'ZEC.4',
      'ZEC.5',
      'ZEC.6',
      'ZEC.7',
      'ZEC.8',
      'ZEC.9',
      'ZEC.10',
      'ZEC.11',
      'ZEC.12',
      'ZEC.13',
      'ZEC.14',
    ],
  },
  {
    id: 'MAL',
    title: 'Malachi',
    abbreviation: 'Mal',
    canon: 'ot',
    chapters: ['MAL.1', 'MAL.2', 'MAL.3', 'MAL.4'],
  },
  {
    id: 'MAT',
    title: 'Matthew',
    abbreviation: 'Matt',
    canon: 'nt',
    chapters: [
      'MAT.1',
      'MAT.2',
      'MAT.3',
      'MAT.4',
      'MAT.5',
      'MAT.6',
      'MAT.7',
      'MAT.8',
      'MAT.9',
      'MAT.10',
      'MAT.11',
      'MAT.12',
      'MAT.13',
      'MAT.14',
      'MAT.15',
      'MAT.16',
      'MAT.17',
      'MAT.18',
      'MAT.19',
      'MAT.20',
      'MAT.21',
      'MAT.22',
      'MAT.23',
      'MAT.24',
      'MAT.25',
      'MAT.26',
      'MAT.27',
      'MAT.28',
    ],
  },
  {
    id: 'MRK',
    title: 'Mark',
    abbreviation: 'Mark',
    canon: 'nt',
    chapters: [
      'MRK.1',
      'MRK.2',
      'MRK.3',
      'MRK.4',
      'MRK.5',
      'MRK.6',
      'MRK.7',
      'MRK.8',
      'MRK.9',
      'MRK.10',
      'MRK.11',
      'MRK.12',
      'MRK.13',
      'MRK.14',
      'MRK.15',
      'MRK.16',
    ],
  },
  {
    id: 'LUK',
    title: 'Luke',
    abbreviation: 'Luke',
    canon: 'nt',
    chapters: [
      'LUK.1',
      'LUK.2',
      'LUK.3',
      'LUK.4',
      'LUK.5',
      'LUK.6',
      'LUK.7',
      'LUK.8',
      'LUK.9',
      'LUK.10',
      'LUK.11',
      'LUK.12',
      'LUK.13',
      'LUK.14',
      'LUK.15',
      'LUK.16',
      'LUK.17',
      'LUK.18',
      'LUK.19',
      'LUK.20',
      'LUK.21',
      'LUK.22',
      'LUK.23',
      'LUK.24',
    ],
  },
  {
    id: 'JHN',
    title: 'John',
    abbreviation: 'John',
    canon: 'nt',
    chapters: [
      'JHN.1',
      'JHN.2',
      'JHN.3',
      'JHN.4',
      'JHN.5',
      'JHN.6',
      'JHN.7',
      'JHN.8',
      'JHN.9',
      'JHN.10',
      'JHN.11',
      'JHN.12',
      'JHN.13',
      'JHN.14',
      'JHN.15',
      'JHN.16',
      'JHN.17',
      'JHN.18',
      'JHN.19',
      'JHN.20',
      'JHN.21',
    ],
  },
  {
    id: 'ACT',
    title: 'Acts',
    abbreviation: 'Acts',
    canon: 'nt',
    chapters: [
      'ACT.1',
      'ACT.2',
      'ACT.3',
      'ACT.4',
      'ACT.5',
      'ACT.6',
      'ACT.7',
      'ACT.8',
      'ACT.9',
      'ACT.10',
      'ACT.11',
      'ACT.12',
      'ACT.13',
      'ACT.14',
      'ACT.15',
      'ACT.16',
      'ACT.17',
      'ACT.18',
      'ACT.19',
      'ACT.20',
      'ACT.21',
      'ACT.22',
      'ACT.23',
      'ACT.24',
      'ACT.25',
      'ACT.26',
      'ACT.27',
      'ACT.28',
    ],
  },
  {
    id: 'ROM',
    title: 'Romans',
    abbreviation: 'Rom',
    canon: 'nt',
    chapters: [
      'ROM.1',
      'ROM.2',
      'ROM.3',
      'ROM.4',
      'ROM.5',
      'ROM.6',
      'ROM.7',
      'ROM.8',
      'ROM.9',
      'ROM.10',
      'ROM.11',
      'ROM.12',
      'ROM.13',
      'ROM.14',
      'ROM.15',
      'ROM.16',
    ],
  },
  {
    id: '1CO',
    title: '1 Corinthians',
    abbreviation: '1 Cor',
    canon: 'nt',
    chapters: [
      '1CO.1',
      '1CO.2',
      '1CO.3',
      '1CO.4',
      '1CO.5',
      '1CO.6',
      '1CO.7',
      '1CO.8',
      '1CO.9',
      '1CO.10',
      '1CO.11',
      '1CO.12',
      '1CO.13',
      '1CO.14',
      '1CO.15',
      '1CO.16',
    ],
  },
  {
    id: '2CO',
    title: '2 Corinthians',
    abbreviation: '2 Cor',
    canon: 'nt',
    chapters: [
      '2CO.1',
      '2CO.2',
      '2CO.3',
      '2CO.4',
      '2CO.5',
      '2CO.6',
      '2CO.7',
      '2CO.8',
      '2CO.9',
      '2CO.10',
      '2CO.11',
      '2CO.12',
      '2CO.13',
    ],
  },
  {
    id: 'GAL',
    title: 'Galatians',
    abbreviation: 'Gal',
    canon: 'nt',
    chapters: ['GAL.1', 'GAL.2', 'GAL.3', 'GAL.4', 'GAL.5', 'GAL.6'],
  },
  {
    id: 'EPH',
    title: 'Ephesians',
    abbreviation: 'Eph',
    canon: 'nt',
    chapters: ['EPH.1', 'EPH.2', 'EPH.3', 'EPH.4', 'EPH.5', 'EPH.6'],
  },
  {
    id: 'PHP',
    title: 'Philippians',
    abbreviation: 'Phil',
    canon: 'nt',
    chapters: ['PHP.1', 'PHP.2', 'PHP.3', 'PHP.4'],
  },
  {
    id: 'COL',
    title: 'Colossians',
    abbreviation: 'Col',
    canon: 'nt',
    chapters: ['COL.1', 'COL.2', 'COL.3', 'COL.4'],
  },
  {
    id: '1TH',
    title: '1 Thessalonians',
    abbreviation: '1 Thes',
    canon: 'nt',
    chapters: ['1TH.1', '1TH.2', '1TH.3', '1TH.4', '1TH.5'],
  },
  {
    id: '2TH',
    title: '2 Thessalonians',
    abbreviation: '2 Thes',
    canon: 'nt',
    chapters: ['2TH.1', '2TH.2', '2TH.3'],
  },
  {
    id: '1TI',
    title: '1 Timothy',
    abbreviation: '1 Tim',
    canon: 'nt',
    chapters: ['1TI.1', '1TI.2', '1TI.3', '1TI.4', '1TI.5', '1TI.6'],
  },
  {
    id: '2TI',
    title: '2 Timothy',
    abbreviation: '2 Tim',
    canon: 'nt',
    chapters: ['2TI.1', '2TI.2', '2TI.3', '2TI.4'],
  },
  {
    id: 'TIT',
    title: 'Titus',
    abbreviation: 'Titus',
    canon: 'nt',
    chapters: ['TIT.1', 'TIT.2', 'TIT.3'],
  },
  {
    id: 'PHM',
    title: 'Philemon',
    abbreviation: 'Phlm',
    canon: 'nt',
    chapters: ['PHM.1'],
  },
  {
    id: 'HEB',
    title: 'Hebrews',
    abbreviation: 'Heb',
    canon: 'nt',
    chapters: [
      'HEB.1',
      'HEB.2',
      'HEB.3',
      'HEB.4',
      'HEB.5',
      'HEB.6',
      'HEB.7',
      'HEB.8',
      'HEB.9',
      'HEB.10',
      'HEB.11',
      'HEB.12',
      'HEB.13',
    ],
  },
  {
    id: 'JAS',
    title: 'James',
    abbreviation: 'Jas',
    canon: 'nt',
    chapters: ['JAS.1', 'JAS.2', 'JAS.3', 'JAS.4', 'JAS.5'],
  },
  {
    id: '1PE',
    title: '1 Peter',
    abbreviation: '1 Pet',
    canon: 'nt',
    chapters: ['1PE.1', '1PE.2', '1PE.3', '1PE.4', '1PE.5'],
  },
  {
    id: '2PE',
    title: '2 Peter',
    abbreviation: '2 Pet',
    canon: 'nt',
    chapters: ['2PE.1', '2PE.2', '2PE.3'],
  },
  {
    id: '1JN',
    title: '1 John',
    abbreviation: '1 John',
    canon: 'nt',
    chapters: ['1JN.1', '1JN.2', '1JN.3', '1JN.4', '1JN.5'],
  },
  {
    id: '2JN',
    title: '2 John',
    abbreviation: '2 John',
    canon: 'nt',
    chapters: ['2JN.1'],
  },
  {
    id: '3JN',
    title: '3 John',
    abbreviation: '3 John',
    canon: 'nt',
    chapters: ['3JN.1'],
  },
  {
    id: 'JUD',
    title: 'Jude',
    abbreviation: 'Jude',
    canon: 'nt',
    chapters: ['JUD.1'],
  },
  {
    id: 'REV',
    title: 'Revelation',
    abbreviation: 'Rev',
    canon: 'nt',
    chapters: [
      'REV.1',
      'REV.2',
      'REV.3',
      'REV.4',
      'REV.5',
      'REV.6',
      'REV.7',
      'REV.8',
      'REV.9',
      'REV.10',
      'REV.11',
      'REV.12',
      'REV.13',
      'REV.14',
      'REV.15',
      'REV.16',
      'REV.17',
      'REV.18',
      'REV.19',
      'REV.20',
      'REV.21',
      'REV.22',
    ],
  },
];
