export const mockGen1Verse1 = {
  id: '1',
  reference: 'Genesis 1:1',
  book_id: 'GEN',
  chapter_id: '1',
  passage_id: 'GEN.1.1',
};

export const mockGen1Verses = [
  {
    id: '1',
    reference: 'Genesis 1:1',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.1',
  },
  {
    id: '2',
    reference: 'Genesis 1:2',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.2',
  },
  {
    id: '3',
    reference: 'Genesis 1:3',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.3',
  },
  {
    id: '4',
    reference: 'Genesis 1:4',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.4',
  },
  {
    id: '5',
    reference: 'Genesis 1:5',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.5',
  },
  {
    id: '6',
    reference: 'Genesis 1:6',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.6',
  },
  {
    id: '7',
    reference: 'Genesis 1:7',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.7',
  },
  {
    id: '8',
    reference: 'Genesis 1:8',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.8',
  },
  {
    id: '9',
    reference: 'Genesis 1:9',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.9',
  },
  {
    id: '10',
    reference: 'Genesis 1:10',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.10',
  },
  {
    id: '11',
    reference: 'Genesis 1:11',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.11',
  },
  {
    id: '12',
    reference: 'Genesis 1:12',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.12',
  },
  {
    id: '13',
    reference: 'Genesis 1:13',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.13',
  },
  {
    id: '14',
    reference: 'Genesis 1:14',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.14',
  },
  {
    id: '15',
    reference: 'Genesis 1:15',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.15',
  },
  {
    id: '16',
    reference: 'Genesis 1:16',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.16',
  },
  {
    id: '17',
    reference: 'Genesis 1:17',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.17',
  },
  {
    id: '18',
    reference: 'Genesis 1:18',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.18',
  },
  {
    id: '19',
    reference: 'Genesis 1:19',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.19',
  },
  {
    id: '20',
    reference: 'Genesis 1:20',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.20',
  },
  {
    id: '21',
    reference: 'Genesis 1:21',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.21',
  },
  {
    id: '22',
    reference: 'Genesis 1:22',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.22',
  },
  {
    id: '23',
    reference: 'Genesis 1:23',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.23',
  },
  {
    id: '24',
    reference: 'Genesis 1:24',
    book_id: 'GEN',
    chapter_id: '1',
    passage_id: 'GEN.1.24',
  },
];
