import type { Language } from '../types';

export const mockLanguages: Language[] = [
  {
    id: 'en',
    language: 'en',
    script: 'Latn',
    script_name: 'Latin',
    aliases: ['eng'],
    display_names: { en: 'English' },
    scripts: ['Latn'],
    variants: [],
    countries: ['US', 'GB', 'CA', 'AU'],
    text_direction: 'ltr',
    writing_population: 1500000000,
    speaking_population: 1500000000,
    default_bible_version_id: null,
  },
  {
    id: 'es',
    language: 'es',
    script: 'Latn',
    script_name: 'Latin',
    aliases: ['spa'],
    display_names: { en: 'Spanish', es: 'español' },
    scripts: ['Latn'],
    variants: [],
    countries: ['ES', 'MX', 'AR', 'CO'],
    text_direction: 'ltr',
    writing_population: 500000000,
    speaking_population: 500000000,
    default_bible_version_id: null,
  },
  {
    id: 'fr',
    language: 'fr',
    script: 'Latn',
    script_name: 'Latin',
    aliases: ['fra', 'fre'],
    display_names: { en: 'French', fr: 'français' },
    scripts: ['Latn'],
    variants: [],
    countries: ['FR', 'CA', 'BE', 'CH'],
    text_direction: 'ltr',
    writing_population: 300000000,
    speaking_population: 300000000,
    default_bible_version_id: null,
  },
  {
    id: 'de',
    language: 'de',
    script: 'Latn',
    script_name: 'Latin',
    aliases: ['deu', 'ger'],
    display_names: { en: 'German', de: 'Deutsch' },
    scripts: ['Latn'],
    variants: [],
    countries: ['DE', 'AT', 'CH'],
    text_direction: 'ltr',
    writing_population: 100000000,
    speaking_population: 100000000,
    default_bible_version_id: null,
  },
  {
    id: 'sr-Latn',
    language: 'sr',
    script: 'Latn',
    script_name: 'latinica',
    aliases: ['srp'],
    display_names: { en: 'Serbian (Latin)', sr: 'srpski' },
    scripts: ['Latn', 'Cyrl'],
    variants: [],
    countries: ['RS', 'BA', 'ME'],
    text_direction: 'ltr',
    writing_population: 8000000,
    speaking_population: 8000000,
    default_bible_version_id: null,
  },
  // Add more languages to reach 25 for default page size when filtering by 'US'
  ...Array.from({ length: 24 }, (_, i) => ({
    id: `lang${i + 1}`,
    language: `lang${i + 1}`,
    script: 'Latn',
    script_name: null,
    aliases: [],
    display_names: {},
    scripts: ['Latn'],
    variants: [],
    countries: ['US'],
    text_direction: 'ltr' as const,
    writing_population: 1000000,
    speaking_population: 1000000,
    default_bible_version_id: null,
  })),
];
