name: Storybook Tests

on:
  pull_request:
    paths:
      - 'packages/ui/**'
      - 'pnpm-lock.yaml'

jobs:
  visual-tests:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
    env:
      STORYBOOK_YOUVERSION_APP_KEY: ${{ secrets.STORYBOOK_YOUVERSION_APP_KEY }}
    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Run integration tests
        run: cd packages/ui && pnpm run test:integration
        env:
          # # Our tests intentionally need to run on staging API.
          YVP_API_HOST: api-staging.youversion.com
          YVP_APP_KEY: ${{ secrets.YVP_APP_KEY }}
          STORYBOOK_YOUVERSION_API_HOST: api-staging.youversion.com
          STORYBOOK_YOUVERSION_APP_KEY: ${{ secrets.STORYBOOK_YOUVERSION_APP_KEY }}
